### ISSUE TITLE
Minimal-blog: Mdx error on build on fresh project 

### ISSUE THREAD

**Issue by SOHELAHMED7** [LekoArts/gatsby-themes#391]
## Description

I have installed fresh new project using `gatsby new minimal-blog LekoArts/gatsby-starter-minimal-blog` by following guide at https://www.gatsbyjs.org/packages/@lekoarts/gatsby-theme-minimal-blog/#install-as-a-starter

I have made no change in code or config after that

After that on the very first build, I got error

```
$ gatsby clean && gatsby develop --port 8001
info Deleting .cache, public
info Successfully deleted directories
success open and validate gatsby-configs - 0.089s
success load plugins - 1.286s
warn The Google Analytics plugin requires a tracking ID. Did you mean to add it?
success onPreInit - 0.037s
success initialize cache - 0.009s
success copy gatsby files - 0.088s
success onPreBootstrap - 0.016s
success createSchemaCustomization - 0.029s
success source and transform nodes - 1.490s
success building schema - 0.356s
success createPages - 0.090s
success createPagesStatefully - 0.076s
success onPreExtractQueries - 0.005s
success update schema - 0.047s
success extract queries from components - 0.487s
success write out requires - 0.072s
success write out redirect data - 0.005s
success Build manifest and related icons - 0.012s
success onPostBootstrap - 0.055s
⠀
info bootstrap finished - 7.564 s
⠀

 ERROR 

gatsby-plugin-mdx
./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const wrappedElement = wrappers.reduce(
|     (element, plugin) => plugin.wrapRootElement({ element }, {}),
>     <MDXRenderer scope={scopeContexts} isHTMLRenderPass>
|       {body}
|     </MDXRenderer>

warn gatsby-plugin-mdx
configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to
'development' or 'production' to enable defaults for each environment.

 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx
./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const wrappedElement = wrappers.reduce(
|     (element, plugin) => plugin.wrapRootElement({ element }, {}),
>     <MDXRenderer scope={scopeContexts} isHTMLRenderPass>
|       {body}
|     </MDXRenderer>

warn gatsby-plugin-mdx
configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to
'development' or 'production' to enable defaults for each environment.

 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx
./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const wrappedElement = wrappers.reduce(
|     (element, plugin) => plugin.wrapRootElement({ element }, {}),
>     <MDXRenderer scope={scopeContexts} isHTMLRenderPass>
|       {body}
|     </MDXRenderer>

warn gatsby-plugin-mdx
configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to
'development' or 'production' to enable defaults for each environment.

 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx
./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const wrappedElement = wrappers.reduce(
|     (element, plugin) => plugin.wrapRootElement({ element }, {}),
>     <MDXRenderer scope={scopeContexts} isHTMLRenderPass>
|       {body}
|     </MDXRenderer>

warn gatsby-plugin-mdx
configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to
'development' or 'production' to enable defaults for each environment.

 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.


 ERROR 

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.

success run queries - 2.167s - 15/15 6.92/s
success Generating image thumbnails - 7.220s - 7/7 0.97/s
⠀
You can now view minimal-blog in the browser.
⠀
  http://localhost:8001/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8001/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 5.402s
```

Gatsby mdx plugin related error

```

 ERROR 

gatsby-plugin-mdx
./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const wrappedElement = wrappers.reduce(
|     (element, plugin) => plugin.wrapRootElement({ element }, {}),
>     <MDXRenderer scope={scopeContexts} isHTMLRenderPass>
|       {body}
|     </MDXRenderer>

warn gatsby-plugin-mdx
configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to
'development' or 'production' to enable defaults for each environment.
```

However the project is running fine at http://localhost:8001/

I have also updated package `@lekoarts/gatsby-theme-minimal-blog` to `2.3.3`

### Steps to reproduce

 1. `gatsby new minimal-blog LekoArts/gatsby-starter-minimal-blog`
 2. cd minimal-blog
 3. gatsby develop

### Expected result

Mdx related build error should not be produced 

### Actual result

No error or warning during build 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: Linux 4.15 Ubuntu 18    
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.36 => 2.21.9 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.0 
    gatsby-plugin-manifest: ^2.2.3 => 2.4.1 
    gatsby-plugin-netlify: ^2.1.3 => 2.3.0 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.1 
  npmGlobalPackages:
    gatsby-cli: 2.12.0

```

**Comment by SOHELAHMED7** [comment]
On production (I am using Netlify) `gatsby build` is failing

Logs:

```
4:21:25 PM: Executing user command: gatsby build
4:21:28 PM: success open and validate gatsby-configs - 0.061s
4:21:29 PM: success load plugins - 1.691s
4:21:29 PM: warning The Google Analytics plugin requires a tracking ID. Did you mean to add it?
4:21:29 PM: success onPreInit - 0.015s
4:21:29 PM: success delete html and css files from previous builds - 0.020s
4:21:29 PM: success initialize cache - 0.009s
4:21:29 PM: success copy gatsby files - 0.028s
4:21:29 PM: success onPreBootstrap - 0.010s
4:21:29 PM: success createSchemaCustomization - 0.007s
4:21:31 PM: success source and transform nodes - 1.875s
4:21:32 PM: success building schema - 0.631s
4:21:32 PM: success createPages - 0.078s
4:21:32 PM: success createPagesStatefully - 0.063s
4:21:32 PM: success onPreExtractQueries - 0.001s
4:21:32 PM: success update schema - 0.053s
4:21:33 PM: success extract queries from components - 0.434s
4:21:33 PM: success write out requires - 0.004s
4:21:33 PM: success write out redirect data - 0.001s
4:21:33 PM: success Build manifest and related icons - 0.001s
4:21:33 PM: success onPostBootstrap - 0.003s
4:21:33 PM: ⠀
4:21:33 PM: info bootstrap finished - 7.311 s
4:21:33 PM: ⠀
4:22:08 PM: success Building production JavaScript and CSS bundles - 35.311s
4:22:08 PM: success Rewriting compilation hashes - 0.001s
4:22:23 PM: warning Query takes too long:
4:22:23 PM: File path: /opt/build/repo/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/homepage-query.tsx
4:22:23 PM: URL path: /
4:22:23 PM: Context: {
4:22:23 PM:     "formatString": "DD.MM.YYYY"
4:22:23 PM: }
4:22:23 PM: warning Query takes too long:
4:22:23 PM: File path: /opt/build/repo/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/blog-query.tsx
4:22:23 PM: URL path: /blog
4:22:23 PM: Context: {
4:22:23 PM:     "formatString": "DD.MM.YYYY"
4:22:23 PM: }
4:22:23 PM: warning Query takes too long:
4:22:23 PM: File path: /opt/build/repo/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/post-query.tsx
4:22:23 PM: URL path: /introduction-to-defence-against-the-dark-arts
4:22:23 PM: Context: {
4:22:23 PM:     "slug": "/introduction-to-defence-against-the-dark-arts",
4:22:23 PM:     "formatString": "DD.MM.YYYY"
4:22:23 PM: }
4:22:24 PM: warning Query takes too long:
4:22:24 PM: File path: /opt/build/repo/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/post-query.tsx
4:22:24 PM: URL path: /fantastic-beasts-and-where-to-find-them
4:22:24 PM: Context: {
4:22:24 PM:     "slug": "/fantastic-beasts-and-where-to-find-them",
4:22:24 PM:     "formatString": "DD.MM.YYYY"
4:22:24 PM: }
4:23:10 PM: error gatsby-plugin-mdx
4:23:10 PM: ReferenceError: window is not defined
4:23:10 PM:     at evalmachine.<anonymous>:1:1
4:23:10 PM:     at Script.runInContext (vm.js:133:20)
4:23:10 PM:     at Script.runInNewContext (vm.js:139:17)
4:23:10 PM:     at module.exports (/opt/build/repo/node_modules/eval/eval.js:73:12)
4:23:10 PM:     at afterEmit (/opt/build/repo/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
4:23:10 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
4:23:10 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:23:10 PM:     at asyncLib.forEachLimit.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:482:27)
4:23:10 PM:     at /opt/build/repo/node_modules/neo-async/async.js:2818:7
4:23:10 PM:     at done (/opt/build/repo/node_modules/neo-async/async.js:3522:9)
4:23:10 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:10 PM:         This field is intended for use with RSS feed generation.
4:23:10 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:10 PM:         Original error:
4:23:10 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:10 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:10 PM:         This field is intended for use with RSS feed generation.
4:23:10 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:10 PM:         Original error:
4:23:10 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:10 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:10 PM:         This field is intended for use with RSS feed generation.
4:23:10 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:10 PM:         Original error:
4:23:10 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:15 PM: error gatsby-plugin-mdx
4:23:15 PM: ReferenceError: window is not defined
4:23:15 PM:     at evalmachine.<anonymous>:1:1
4:23:15 PM:     at Script.runInContext (vm.js:133:20)
4:23:15 PM:     at Script.runInNewContext (vm.js:139:17)
4:23:15 PM:     at module.exports (/opt/build/repo/node_modules/eval/eval.js:73:12)
4:23:15 PM:     at afterEmit (/opt/build/repo/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
4:23:15 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
4:23:15 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:23:15 PM:     at asyncLib.forEachLimit.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:482:27)
4:23:15 PM:     at /opt/build/repo/node_modules/neo-async/async.js:2818:7
4:23:15 PM:     at done (/opt/build/repo/node_modules/neo-async/async.js:3522:9)
4:23:15 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:15 PM:         This field is intended for use with RSS feed generation.
4:23:15 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:15 PM:         Original error:
4:23:15 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:18 PM: error gatsby-plugin-mdx
4:23:18 PM: ReferenceError: window is not defined
4:23:18 PM:     at evalmachine.<anonymous>:1:1
4:23:18 PM:     at Script.runInContext (vm.js:133:20)
4:23:18 PM:     at Script.runInNewContext (vm.js:139:17)
4:23:18 PM:     at module.exports (/opt/build/repo/node_modules/eval/eval.js:73:12)
4:23:18 PM:     at afterEmit (/opt/build/repo/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
4:23:18 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
4:23:18 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:23:18 PM:     at asyncLib.forEachLimit.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:482:27)
4:23:18 PM:     at /opt/build/repo/node_modules/neo-async/async.js:2818:7
4:23:18 PM:     at done (/opt/build/repo/node_modules/neo-async/async.js:3522:9)
4:23:18 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:18 PM:         This field is intended for use with RSS feed generation.
4:23:18 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:18 PM:         Original error:
4:23:18 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:18 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:18 PM:         This field is intended for use with RSS feed generation.
4:23:18 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:18 PM:         Original error:
4:23:18 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:18 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:18 PM:         This field is intended for use with RSS feed generation.
4:23:18 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:18 PM:         Original error:
4:23:18 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:18 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:18 PM:         This field is intended for use with RSS feed generation.
4:23:18 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:18 PM:         Original error:
4:23:18 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:19 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:19 PM:         This field is intended for use with RSS feed generation.
4:23:19 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:19 PM:         Original error:
4:23:19 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:19 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:19 PM:         This field is intended for use with RSS feed generation.
4:23:19 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:19 PM:         Original error:
4:23:19 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:19 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:19 PM:         This field is intended for use with RSS feed generation.
4:23:19 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:19 PM:         Original error:
4:23:19 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:19 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:19 PM:         This field is intended for use with RSS feed generation.
4:23:19 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:19 PM:         Original error:
4:23:19 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:19 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:19 PM:         This field is intended for use with RSS feed generation.
4:23:19 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:19 PM:         Original error:
4:23:19 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:21 PM: error gatsby-plugin-mdx
4:23:21 PM: ReferenceError: window is not defined
4:23:21 PM:     at evalmachine.<anonymous>:1:1
4:23:21 PM:     at Script.runInContext (vm.js:133:20)
4:23:21 PM:     at Script.runInNewContext (vm.js:139:17)
4:23:21 PM:     at module.exports (/opt/build/repo/node_modules/eval/eval.js:73:12)
4:23:21 PM:     at afterEmit (/opt/build/repo/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
4:23:21 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
4:23:21 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:23:21 PM:     at asyncLib.forEachLimit.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:482:27)
4:23:21 PM:     at /opt/build/repo/node_modules/neo-async/async.js:2818:7
4:23:21 PM:     at done (/opt/build/repo/node_modules/neo-async/async.js:3522:9)
4:23:21 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:21 PM:         This field is intended for use with RSS feed generation.
4:23:21 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:21 PM:         Original error:
4:23:21 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:21 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:21 PM:         This field is intended for use with RSS feed generation.
4:23:21 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:21 PM:         Original error:
4:23:21 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:21 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:21 PM:         This field is intended for use with RSS feed generation.
4:23:21 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:21 PM:         Original error:
4:23:21 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:21 PM: success run queries - 108.776s - 15/15 0.14/s
4:23:27 PM: success Building static HTML for pages - 5.400s - 13/13 2.41/s
4:23:27 PM: success Generating image thumbnails - 116.063s - 7/7 0.06/s
4:23:27 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:27 PM:         This field is intended for use with RSS feed generation.
4:23:27 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:27 PM:         Original error:
4:23:27 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:27 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:27 PM:         This field is intended for use with RSS feed generation.
4:23:27 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:27 PM:         Original error:
4:23:27 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:27 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:27 PM:         This field is intended for use with RSS feed generation.
4:23:27 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:27 PM:         Original error:
4:23:27 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:27 PM: error gatsby-plugin-mdx: Error querying the `html` field.
4:23:27 PM:         This field is intended for use with RSS feed generation.
4:23:27 PM:         If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
4:23:27 PM:         Original error:
4:23:27 PM:         Error: renderMdxBody was unavailable when rendering html.
4:23:27 PM: error "gatsby-plugin-feed" threw an error while running the onPostBuild lifecycle:
4:23:27 PM: Cannot return null for non-nullable field MdxPost.html.
4:23:27 PM: GraphQL request:9:15
4:23:27 PM:  8 |               slug
4:23:27 PM:  9 |               html
4:23:27 PM:    |               ^
4:23:27 PM: 10 |             }
4:23:27 PM: 
4:23:27 PM:   Error: Cannot return null for non-nullable field MdxPost.html.
4:23:27 PM:   GraphQL request:9:15
4:23:27 PM:    8 |               slug
4:23:27 PM:    9 |               html
4:23:27 PM:      |               ^
4:23:27 PM:   10 |             }
4:23:27 PM:   
4:23:27 PM:   - internals.js:15 
4:23:27 PM:     [repo]/[gatsby-plugin-feed]/internals.js:15:13
4:23:27 PM:   
4:23:27 PM:   - next_tick.js:68 process._tickCallback
4:23:27 PM:     internal/process/next_tick.js:68:7
4:23:27 PM:   
4:23:27 PM: 
4:23:27 PM: not finished onPostBuild - 0.056s
4:23:27 PM: Skipping functions preparation step: no functions directory set
4:23:27 PM: Caching artifacts
4:23:27 PM: Started saving node modules
4:23:27 PM: Finished saving node modules
4:23:27 PM: Started saving pip cache
4:23:27 PM: Finished saving pip cache
4:23:27 PM: Started saving emacs cask dependencies
4:23:27 PM: Finished saving emacs cask dependencies
4:23:27 PM: Started saving maven dependencies
4:23:27 PM: Finished saving maven dependencies
4:23:27 PM: Started saving boot dependencies
4:23:27 PM: Finished saving boot dependencies
4:23:27 PM: Started saving go dependencies
4:23:27 PM: Finished saving go dependencies
4:23:31 PM: Error running command: Build script returned non-zero exit code: 1
4:23:31 PM: Failing build: Failed to build site
4:23:32 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
4:23:32 PM: Finished processing build request in 3m18.622328779s
```

**Comment by SOHELAHMED7** [comment]
In my local end `gatsby build` is giving me success. I think the different version of npm package is a problem?

**Comment by LekoArts** [comment]
A recent version of `gatsby-plugin-mdx` introduced this problem. See https://github.com/gatsbyjs/gatsby/issues/23614 and https://github.com/gatsbyjs/gatsby/issues/23714

You can pin your local version to `1.2.1` by using `resolutions` from yarn. Here's an example:

https://github.com/LekoArts/minimal-blog-additional-field/blob/master/package.json#L32-L34

I'll see that `1.2.5` will be released tomorrow and then I'll update my themes. I don't want to pin versions really if it only makes a difference of one day.
