### ISSUE TITLE
[gatsby-starter-minimal-blog]: Fresh install, Error: Cannot find module '@gatsbyjs/reach-router/lib/utils'

### ISSUE THREAD

**Issue by princefishthrower** [LekoArts/gatsby-themes#625]
## Description

Error on after issuing very first `gatsby develop`

### Steps to reproduce

Standard install process:

```
gatsby new my-site https://github.com/LekoArts/gatsby-starter-minimal-blog
cd my-site
gatsby develop
```

### Expected result

Site should start running and open up at `localhost:8000`!

### Actual result

Error:

```
/my-computer/my-site/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '@gatsbyjs/reach-router/lib/utils'
Require stack:
- /my-computer/my-site/node_modules/gatsby/dist/utils/find-page-by-path.js
- /my-computer/my-site/node_modules/gatsby/dist/utils/websocket-manager.js
- /my-computer/my-site/node_modules/gatsby/dist/utils/page-data.js
- /my-computer/my-site/node_modules/gatsby/dist/utils/webpack-status.js
- /my-computer/my-site/node_modules/gatsby/dist/commands/develop-process.js
- /my-computer/my-site/.cache/tmp-21090-B6Ji53HbDmix
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/my-computer/my-site/node_modules/gatsby/src/utils/find-page-by-path.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/my-computer/my-site/node_modules/gatsby/dist/utils/find-page-by-path.js',
    '/my-computer/my-site/node_modules/gatsby/dist/utils/websocket-manager.js',
    '/my-computer/my-site/node_modules/gatsby/dist/utils/page-data.js',
    '/my-computer/my-site/node_modules/gatsby/dist/utils/webpack-status.js',
    '/my-computer/my-site/node_modules/gatsby/dist/commands/develop-process.js',
    '/my-computer/my-site/.cache/tmp-21090-B6Ji53HbDmix'
  ]
}
```

### Environment

```
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nodenv/shims/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nodenv/shims/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.1 => 3.9.0
    gatsby-omni-font-loader: ^1.3.1 => 1.3.1
    gatsby-plugin-feed: ^3.6.0 => 3.9.0
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.9.0
    gatsby-plugin-google-analytics: ^3.6.0 => 3.9.0
    gatsby-plugin-manifest: ^3.6.0 => 3.9.0
    gatsby-plugin-netlify: ^3.6.1 => 3.9.0
    gatsby-plugin-offline: ^4.6.0 => 4.9.0
    gatsby-plugin-sitemap: ^4.2.0 => 4.5.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.24
  npmGlobalPackages:
    gatsby: 3.9.0
```

As an aside, how do the header and footer actually work on this template? I can't find them in the source anywhere!

**Comment by LekoArts** [comment]
Hi! Please see https://github.com/LekoArts/gatsby-themes/issues/624 and https://github.com/LekoArts/gatsby-themes/discussions/613. This is an issue with npm 7 and how it breaks working projects due to some peerDeps. `gatsby new` doesn't use `--legacy-peer-deps` so you'll need to do this manually.

> As an aside, how do the header and footer actually work on this template? I can't find them in the source anywhere!

They are here:
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/header.tsx
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/footer.tsx

You'll want to _shadow_ those if you want to modify them in your site.

**Comment by princefishthrower** [comment]
@LekoArts - excellent, thanks for the swift response!
